mixed-port: 7890
tproxy-port: 7893
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ./ui
routing-mark: 9

profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - '+.stun.*.*'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    - '.ipv6.microsoft.com'
    - 'localhost.ptlogin2.qq.com'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '*.mcdn.bilivideo.cn'
  nameserver:
    - tls://223.5.5.5
  nameserver-policy:
    '+.taobao.com': '223.5.5.5'
    '+.qq.com': '119.29.29.29'
